// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTmUK_4di8HJuOpPJFBiJw8oRAValBuB0',
    appId: '1:774194407653:web:f5f9682820102cd5d80c0c',
    messagingSenderId: '774194407653',
    projectId: 'seeme-test',
    authDomain: 'seeme-test.firebaseapp.com',
    databaseURL: 'https://seeme-test-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-test.appspot.com',
    measurementId: 'G-13WEL9ZDCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMAF88fryJjgNdleWtAoEsZphsCpDiRE',
    appId: '1:774194407653:android:77c84426bdf90db0d80c0c',
    messagingSenderId: '774194407653',
    projectId: 'seeme-test',
    databaseURL: 'https://seeme-test-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRFycLjHvnSf-Q16BlQXHckntzwNJcWE',
    appId: '1:774194407653:ios:b354331cbf43155ad80c0c',
    messagingSenderId: '774194407653',
    projectId: 'seeme-test',
    databaseURL: 'https://seeme-test-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-test.appspot.com',
    iosClientId: '774194407653-8vqidnpu6oh9s2oj5hdl39111i34nj7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.seemeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRFycLjHvnSf-Q16BlQXHckntzwNJcWE',
    appId: '1:774194407653:ios:b354331cbf43155ad80c0c',
    messagingSenderId: '774194407653',
    projectId: 'seeme-test',
    databaseURL: 'https://seeme-test-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-test.appspot.com',
    iosClientId: '774194407653-8vqidnpu6oh9s2oj5hdl39111i34nj7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.seemeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTmUK_4di8HJuOpPJFBiJw8oRAValBuB0',
    appId: '1:774194407653:web:286e53d8bc918543d80c0c',
    messagingSenderId: '774194407653',
    projectId: 'seeme-test',
    authDomain: 'seeme-test.firebaseapp.com',
    databaseURL: 'https://seeme-test-default-rtdb.firebaseio.com',
    storageBucket: 'seeme-test.appspot.com',
    measurementId: 'G-Q8GMN9VZKY',
  );

}